### ISSUE TITLE
Can't seem to build a valid compilation

### ISSUE THREAD

**Issue by patters-match** [FluBBaOfWard/NGPGBA#1]
[ngpadvance_compile.py.zip](https://github.com/FluBBaOfWard/NGPGBA/files/9804894/ngpadvance_compile.py.zip)

I have tried adapting my existing ngpadvance Python 3 builder for this NGPGBA emulator but it doesn't seem to work (see attached). As far as I can see the headers produced look compliant to your example _ngp.header_ file.

When I run the test compilation I see some kind of BIOS (which is odd, because I see this whether or not I include one in my test compilation) with the text "No Roms Found." overlaid on the display output. Am I missing something obvious?

**Comment by FluBBaOfWard** [comment]
I forgot to change the SMSID to NGPID, should hopefully be fixed now.

**Comment by patters-match** [comment]
I see, it works now.

I fixed a couple of silly bugs in the builder (I see your newer GBA emus no longer support splash screens, and there was a reference to a misnamed variable when adding a 'boot-to-BIOS' entry).
[ngpadvance_compile.py.zip](https://github.com/FluBBaOfWard/NGPGBA/files/9814485/ngpadvance_compile.py.zip)

However, I notice that the emulator doesn't currently work with either the NGP or the NGC BIOS files which do apparently work on ngpadvance. Can you check that? The builder is apparently setting the bios bit as per the spec.

I see there are speed hacks for many ROMs in your todo list - do you expect that these will make a big difference to performance, like they did for PCEAdvance?

**Comment by FluBBaOfWard** [comment]
I don't think the BIOSes worked on ngpadvance, I worked a lot to get it to work on the NDS. What happens is it tries to write to the cartridge to make sure the flash works, and if it doesn't, refuse to boot the game. I guess it can be fixed some how...
I will try to add support for splash screens later on. Closing this now.
